repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-merge-conflict
      - id: no-commit-to-branch
        name: Don't commit to main
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-ast
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.812
    hooks:
      - id: mypy
        name: Check Type Hinting using MyPy
  - repo: https://github.com/terrencepreilly/darglint
    rev: v1.8.0
    hooks:
      - id: darglint
        name: Ensure Google DocString formatting using DargLint
  - repo: https://github.com/pycqa/isort
    rev: 5.8.0
    hooks:
      - id: isort
        name: Sort arguments using iSort
        args: [-p=nory, -p=tests, --line-length=79, --profile=black]
  - repo: https://github.com/ambv/black
    rev: 20.8b1
    hooks:
      - id: black
        name: Format using Black
        description: "Black: The uncompromising Python code formatter"
        entry: black
        language: python
        require_serial: true
        language_version: python3.8
        types: [ python ]
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.0
    hooks:
      - id: flake8
        name: Check PEP8 compliance
        description: "Flake8: Your Tool For Style Guide Enforcement"
        entry: flake8 .
        language: python
        require_serial: true
        language_version: python3.8
        types: [ python ]
