org: gapper100
app: cbbi-bot
service: telegram-bot
frameworkVersion: '^2.39.1'
provider:
  name: aws
  runtime: python3.8
  region: eu-west-1
  environment:
    TELEGRAM_TOKEN: ${param:TELEGRAM_TOKEN, env:TELEGRAM_TOKEN}
    TELEGRAM_CRYPTO_CHAT_ID: ${param:TELEGRAM_CRYPTO_CHAT_ID, env:TELEGRAM_CRYPTO_CHAT_ID_TEST}
    TELEGRAM_CBBI_CHANNEL_ID: ${param:TELEGRAM_CBBI_CHANNEL_ID, env:TELEGRAM_CBBI_CHANNEL_ID_TEST}
  lambdaHashingVersion: 20201221
functions:
  cron:
    handler: cbbi_bot/handler.send_message
    events:
      # Invoke Lambda function (production at 8:00 UTC every day)
      - schedule: cron(00 8 * * ? *)
plugins:
  - serverless-python-requirements
